version: '3.7'

services:
  emqx:
    image: emqx/emqx:latest
    container_name: emqx
    ports:
      - 1883:1883
      - 8883:8883
      - 8083:8083
      - 8084:8084
      - 18083:18083
    restart: always
    env_file:
      - ./default.env
    volumes:
      - ${PWD}/data:/opt/emqx/data
      - ${PWD}/cert.pem:/opt/emqx/cert.pem
      - ${PWD}/key.pem:/opt/emqx/key.pem
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:18083"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - backend

networks:
  backend:
    external:
      name: backend
